# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mlops_pb2 as mlops__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mlops_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLModelServiceStub(object):
    """Service for ML model management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/mlops.MLModelService/HealthCheck',
                request_serializer=mlops__pb2.HealthRequest.SerializeToString,
                response_deserializer=mlops__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetAvailableModels = channel.unary_unary(
                '/mlops.MLModelService/GetAvailableModels',
                request_serializer=mlops__pb2.Empty.SerializeToString,
                response_deserializer=mlops__pb2.AvailableModelsResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/mlops.MLModelService/ListModels',
                request_serializer=mlops__pb2.Empty.SerializeToString,
                response_deserializer=mlops__pb2.ModelsListResponse.FromString,
                _registered_method=True)
        self.TrainModel = channel.unary_unary(
                '/mlops.MLModelService/TrainModel',
                request_serializer=mlops__pb2.TrainRequest.SerializeToString,
                response_deserializer=mlops__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/mlops.MLModelService/Predict',
                request_serializer=mlops__pb2.PredictRequest.SerializeToString,
                response_deserializer=mlops__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.RetrainModel = channel.unary_unary(
                '/mlops.MLModelService/RetrainModel',
                request_serializer=mlops__pb2.RetrainRequest.SerializeToString,
                response_deserializer=mlops__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/mlops.MLModelService/DeleteModel',
                request_serializer=mlops__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=mlops__pb2.DeleteModelResponse.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/mlops.MLModelService/ListDatasets',
                request_serializer=mlops__pb2.Empty.SerializeToString,
                response_deserializer=mlops__pb2.DatasetsListResponse.FromString,
                _registered_method=True)


class MLModelServiceServicer(object):
    """Service for ML model management
    """

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableModels(self, request, context):
        """Get available model classes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List all trained models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Train a new model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Get predictions from a model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrainModel(self, request, context):
        """Retrain an existing model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Delete a model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """List datasets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=mlops__pb2.HealthRequest.FromString,
                    response_serializer=mlops__pb2.HealthResponse.SerializeToString,
            ),
            'GetAvailableModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableModels,
                    request_deserializer=mlops__pb2.Empty.FromString,
                    response_serializer=mlops__pb2.AvailableModelsResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=mlops__pb2.Empty.FromString,
                    response_serializer=mlops__pb2.ModelsListResponse.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=mlops__pb2.TrainRequest.FromString,
                    response_serializer=mlops__pb2.TrainResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=mlops__pb2.PredictRequest.FromString,
                    response_serializer=mlops__pb2.PredictResponse.SerializeToString,
            ),
            'RetrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrainModel,
                    request_deserializer=mlops__pb2.RetrainRequest.FromString,
                    response_serializer=mlops__pb2.TrainResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=mlops__pb2.DeleteModelRequest.FromString,
                    response_serializer=mlops__pb2.DeleteModelResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=mlops__pb2.Empty.FromString,
                    response_serializer=mlops__pb2.DatasetsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlops.MLModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlops.MLModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLModelService(object):
    """Service for ML model management
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops.MLModelService/HealthCheck',
            mlops__pb2.HealthRequest.SerializeToString,
            mlops__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops.MLModelService/GetAvailableModels',
            mlops__pb2.Empty.SerializeToString,
            mlops__pb2.AvailableModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops.MLModelService/ListModels',
            mlops__pb2.Empty.SerializeToString,
            mlops__pb2.ModelsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops.MLModelService/TrainModel',
            mlops__pb2.TrainRequest.SerializeToString,
            mlops__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops.MLModelService/Predict',
            mlops__pb2.PredictRequest.SerializeToString,
            mlops__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops.MLModelService/RetrainModel',
            mlops__pb2.RetrainRequest.SerializeToString,
            mlops__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops.MLModelService/DeleteModel',
            mlops__pb2.DeleteModelRequest.SerializeToString,
            mlops__pb2.DeleteModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops.MLModelService/ListDatasets',
            mlops__pb2.Empty.SerializeToString,
            mlops__pb2.DatasetsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

